### ISSUE TITLE
Invalid peerDependencies?

### ISSUE THREAD

**Issue by Snurppa** [Unbuttun/fastify-slonik#97]
Hi,

in this recent commit https://github.com/spa5k/fastify-slonik/pull/93/commits/2e5131616980a837ce07ca60264c33025400d3f9 peer deps were bumped, but isn't the `< "4.x"` wrong if this should support Fastify v4?

I am getting error following error when I try to install this with latest Fastify (same issue was with pre-v4, but back then I just discarded it with `--legacy-peer-deps`):

```
$ npm i fastify-slonik -w ./api
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: foo@1.0.0
npm ERR! Found: fastify@4.5.3
npm ERR! node_modules/fastify
npm ERR!   fastify@"~4.5.3" from foo@1.0.0
npm ERR!   api
npm ERR!     foo@1.0.0
npm ERR!     node_modules/foo
npm ERR!       workspace api from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer fastify@"< 4.x" from fastify-slonik@1.7.0

npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Using npm `8.18.0`.

I would not like to do the `--legacy-peer-deps` anymore, as this seems to be obvious thing, though I am not that familiar with the ecosystem tbh.

Also [`slonik`](https://www.npmjs.com/package/slonik) is already in v31.X.X. So I am wondering is this plugin really dependent on "smaller than Slonik v28", or would it be wise to re-consider what kind of peer dep version locks should this plugin include?

Seems Slonik versions are going up in pretty fast pace, so kind of worried if these peerDependencies issues would hinder the popularity of this plugin.

Thanks!

**Comment by spa5k** [comment]
slonik releases major version faster than even browsers, the developer should at least consider.

**Comment by spa5k** [comment]
its probably fixed now in latest major version, 2, try it.
